-- Migration: Create REL_CONTAS_RECEBER table
-- Description: Creates the table for Accounts Receivable with structure matching the provided dataset.

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.rel_contas_receber (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Dataset Columns
    agn_in_codigo BIGINT,
    cre_st_documento TEXT,
    cre_st_parcela TEXT,
    dt_baixa DATE,
    dt_lancamento DATE,
    dt_vencto DATE,
    fpa_dt_emissao DATE,
    fpa_st_doctointerno TEXT,
    fpa_st_favorecido TEXT,
    fre_in_numero BIGINT,
    fre_tpd_st_codigo TEXT,
    mov_ch_conciliado TEXT,
    mov_ch_natureza TEXT,
    mov_in_numlancto BIGINT,
    mov_re_saldocpacre NUMERIC(15, 2),
    org_in_codigo BIGINT,
    rcb_st_nota TEXT,
    valor NUMERIC(15, 2),

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Indexes for performance
CREATE INDEX IF NOT EXISTS idx_rel_contas_receber_vencto ON public.rel_contas_receber (dt_vencto);
CREATE INDEX IF NOT EXISTS idx_rel_contas_receber_lancamento ON public.rel_contas_receber (dt_lancamento);
CREATE INDEX IF NOT EXISTS idx_rel_contas_receber_numlancto ON public.rel_contas_receber (mov_in_numlancto);

-- 3. Add Unique Constraint for Upserts (assuming mov_in_numlancto is unique identifier)
-- If there is an Organization/Branch code that makes it unique combined, it should be added here.
-- Based on the provided list, we only have ORG_IN_CODIGO. 
-- We will add a constraint on mov_in_numlancto for now.
ALTER TABLE public.rel_contas_receber DROP CONSTRAINT IF EXISTS unique_receivable_record;
ALTER TABLE public.rel_contas_receber ADD CONSTRAINT unique_receivable_record UNIQUE (mov_in_numlancto);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.rel_contas_receber ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies (Permissive for now, matching existing setup)
DROP POLICY IF EXISTS "Acesso Publico Leitura Receber" ON public.rel_contas_receber;
CREATE POLICY "Acesso Publico Leitura Receber" ON public.rel_contas_receber FOR SELECT USING (true);

DROP POLICY IF EXISTS "Acesso Publico Escrita Receber" ON public.rel_contas_receber;
CREATE POLICY "Acesso Publico Escrita Receber" ON public.rel_contas_receber FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Acesso Publico Atualizacao Receber" ON public.rel_contas_receber;
CREATE POLICY "Acesso Publico Atualizacao Receber" ON public.rel_contas_receber FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Acesso Publico Delecao Receber" ON public.rel_contas_receber;
CREATE POLICY "Acesso Publico Delecao Receber" ON public.rel_contas_receber FOR DELETE USING (true);

-- 6. Grant Permissions
GRANT USAGE, SELECT ON SEQUENCE rel_contas_receber_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE rel_contas_receber_id_seq TO authenticated;
GRANT ALL ON TABLE public.rel_contas_receber TO anon;
GRANT ALL ON TABLE public.rel_contas_receber TO authenticated;
GRANT ALL ON TABLE public.rel_contas_receber TO service_role;
