-- RECOMENDAÇÃO: Apague a tabela antiga antes de rodar este script para garantir a nova estrutura.
-- DROP TABLE IF EXISTS public.rel_financeiro;

CREATE TABLE IF NOT EXISTS public.rel_financeiro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Colunas Originais
    agn_in_codigo BIGINT,
    valor NUMERIC(15, 2),
    mov_dt_vencto DATE,
    mov_dt_datadocto DATE,
    mov_ch_natureza TEXT,
    fpa_st_favorecido TEXT,
    mov_ch_conciliado TEXT,
    fil_in_codigo BIGINT,
    rcb_st_nota TEXT,

    -- Novas Colunas do Dataset
    cheqbx_re_vrbaixa NUMERIC(15, 2),
    cheqbx_re_vrjuros NUMERIC(15, 2),
    conta_baixa BIGINT,
    cpa_in_ap BIGINT,
    cpa_st_documento TEXT,
    cpa_st_parcela TEXT,
    fpa_dt_emissao DATE,
    fpa_in_contador BIGINT,
    fpa_in_numero BIGINT,
    fpa_st_doctointerno TEXT,
    fpa_tpd_st_codigo TEXT,
    mov_in_numlancto BIGINT,
    mov_re_saldocpacre NUMERIC(15, 2),
    org_in_codigo BIGINT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_rel_financeiro_vencto ON public.rel_financeiro (mov_dt_vencto);

-- Permissões (RLS)
ALTER TABLE public.rel_financeiro ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Acesso Publico Leitura" ON public.rel_financeiro;
CREATE POLICY "Acesso Publico Leitura" ON public.rel_financeiro FOR SELECT USING (true);

DROP POLICY IF EXISTS "Acesso Publico Escrita" ON public.rel_financeiro;
CREATE POLICY "Acesso Publico Escrita" ON public.rel_financeiro FOR INSERT WITH CHECK (true);

GRANT USAGE, SELECT ON SEQUENCE rel_financeiro_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE rel_financeiro_id_seq TO authenticated;